POST http://localhost:5500/items
Content-Type: application/json

{
  "item": "Prueba nueva Controller 1"
}

### 

GET http://localhost:5500/items
Content-Type: application/json

### 

PATCH http://localhost:5500/items/644673b5b25b7eff89b7f288
Content-Type: application/json

{
  "item": "Prueba nueva Controller 1 update"
}

### 

DELETE http://localhost:5500/items/64467646cbf6d15c71ce3139

